name: release
on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release install script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "install.sh"
