name: test
on: [push, pull_request]
jobs:

  test-error-handling:
    name: "Test install script's error handling"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Test the install script's error handling"
      run: diff <(./test_errors.sh ./install.sh) test_errors.expected_output

  test-docker:
    name: "Test installing dune into docker image"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Test that the install script can install a working dune into a docker image"
      run: docker build . -f test.dockerfile

  test-interactive:
    name: "Test install script interactively"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install deps for interactive test"
      run: |
        sudo apt-get update
        sudo apt-get install -y curl expect
    - name: "Test the script interactively"
      run: ./test_interactive.tcl

  shellcheck:
    name: "Run shellcheck on all shell scripts"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install shellcheck"
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: "Run shellcheck on all shell scripts"
      run: shellcheck *.sh

  shellcheck-on-generated-bash:
    name: "Run shellcheck on the generated shell config for bash"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install shellcheck"
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: "Initialize shell config with shebang so shellcheck knows it's bash"
      run: echo '#!/usr/bin/env bash' > ~/.profile
    - name: "Generated a shell config by installing the binary distro"
      run: ./install.sh 3.19.1 --install-root ~/.local --update-shell-config --shell bash --shell-config ~/.profile
    - name: "Run shellcheck on the generated shell config"
      run: shellcheck --exclude=SC1091 ~/.profile
